{
 "title": "NEAR General dashboard",
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   { "name": "account_id", "query": "inc4.factory.shardnet.near" },
   { "name": "job", "query": "near" }
  ]
 },
 "panels": [
  {
   "title": "Total Transactions",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 1, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "near_transaction_processed_successfully_total"
    }
   ]
  },
  {
   "title": "Is Validator",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 7, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "near_is_validator" }
   ]
  },
  {
   "title": "Blocks Per Minute",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 6, "x": 11, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(near_blocks_per_minute[$__rate_interval])"
    }
   ]
  },
  {
   "title": "Processed Total Transactions",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 6, "x": 17, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(near_transaction_processed_total[$__rate_interval])"
    }
   ]
  },
  {
   "title": "Block Height",
   "type": "stat",
   "gridPos": { "h": 5, "w": 7, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "near_block_height_head" }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 7, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "near_validators_blocks_produced{account_id=\"$account_id\",job=\"$job\"} / near_validators_blocks_expected{account_id=\"$account_id\",job=\"$job\"}",
     "legendFormat": "Blocks"
    },
    {
     "expr": "near_validators_chunks_produced{account_id=\"$account_id\",job=\"$job\"} / near_validators_chunks_expected{account_id=\"$account_id\",job=\"$job\"}",
     "legendFormat": "Chunks"
    }
   ]
  },
  {
   "title": "Block Processed",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 7, "x": 16, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(near_block_processed_total[$__rate_interval])"
    }
   ]
  },
  {
   "title": "Block Processing",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 9, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "rate(near_block_processing_time_count[$__rate_interval])"
    }
   ]
  },
  {
   "title": "Blocks Per Minute",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 7, "x": 9, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "expr": "near_blocks_per_minute" }
   ]
  },
  {
   "title": "Processed Successfully Transactions",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(near_transaction_processed_successfully_total[$__rate_interval])"
    }
   ]
  },
  {
   "title": "Reachable Peers",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 4, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "near_peer_reachable" }
   ]
  },
  {
   "title": "Transactions Pool Entries ",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 7, "x": 9, "y": 19 },
   "targets": [
    { "expr": "near_transaction_pool_entries", "legendFormat": "Chunk" }
   ]
  },
  {
   "title": "Block Processing Time Count",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 7, "x": 16, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(near_block_processing_time_count[$__rate_interval])"
    }
   ]
  }
 ]
}