{
 "title": "NEAR Validator dasboard",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "account_id", "query": "inc4.factory.shardnet.near" },
   { "name": "job", "query": "near" }
  ]
 },
 "panels": [
  {
   "title": "Missed blocks",
   "type": "stat",
   "gridPos": { "h": 7, "w": 3, "x": 1, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "near_validators_blocks_expected{account_id=\"$account_id\",job=\"$job\"} - near_validators_blocks_produced{account_id=\"$account_id\",job=\"$job\"}",
     "legendFormat": "Count"
    }
   ]
  },
  {
   "title": "Missed chunks",
   "type": "stat",
   "gridPos": { "h": 7, "w": 3, "x": 4, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "near_validators_chunks_expected{account_id=\"$account_id\",job=\"$job\"} - near_validators_chunks_produced{account_id=\"$account_id\",job=\"$job\"}",
     "legendFormat": "Missed"
    }
   ]
  },
  {
   "title": "Is Validator",
   "type": "stat",
   "gridPos": { "h": 7, "w": 3, "x": 8, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "near_is_validator" }
   ]
  },
  {
   "title": "Is Validator",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 4, "x": 11, "y": 0 },
   "targets": [
    {
     "expr": "near_is_validator{job=\"$job\"}",
     "legendFormat": "State"
    }
   ]
  },
  {
   "title": "Percent of produced ",
   "type": "stat",
   "gridPos": { "h": 7, "w": 5, "x": 15, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "near_validators_blocks_produced{account_id=\"$account_id\",job=\"$job\"} / near_validators_blocks_expected{account_id=\"$account_id\",job=\"$job\"}",
     "legendFormat": "Blocks"
    },
    {
     "expr": "near_validators_chunks_produced{account_id=\"$account_id\",job=\"$job\"} / near_validators_chunks_expected{account_id=\"$account_id\",job=\"$job\"}",
     "legendFormat": "Chunks"
    }
   ]
  },
  {
   "title": "Chunk",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 10, "x": 1, "y": 7 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(near_chunk_tgas_used_hist_bucket[$__rate_interval])) by (le))",
     "legendFormat": "Chunk"
    }
   ]
  },
  {
   "title": "Chunks",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 9, "x": 11, "y": 7 },
   "targets": [
    {
     "expr": "near_validators_chunks_expected{account_id=\"$account_id\",job=\"$job\"}",
     "legendFormat": "validator chunks expected"
    },
    {
     "expr": "near_validators_chunks_produced{account_id=\"$account_id\",job=\"$job\"}",
     "legendFormat": "validator chunks produced"
    }
   ]
  },
  {
   "title": "Peers",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 1, "y": 16 },
   "targets": [
    { "expr": "near_peer_connections_total", "legendFormat": "Peers" }
   ]
  },
  {
   "title": "Total Staked",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 11, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "near_validators_stake_total{job=\"$job\"}",
     "legendFormat": "NEAR Tokens"
    }
   ]
  },
  {
   "title": "Blocks",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 1, "y": 24 },
   "targets": [
    {
     "expr": "near_validators_blocks_expected{account_id=\"$account_id\",job=\"$job\"}",
     "legendFormat": "validator blocks expected"
    },
    {
     "expr": "near_validators_blocks_produced{account_id=\"$account_id\",job=\"$job\"}",
     "legendFormat": "validator blocks produced"
    }
   ]
  },
  {
   "title": "Avg transaction gas cost",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 7, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(near_gas_used{job=\"$job\"}[1m]) / rate(near_transaction_processed_total{job=\"$job\"}[1m])",
     "legendFormat": "Gas"
    }
   ]
  },
  {
   "title": "Active validators",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 13, "y": 24 },
   "targets": [
    {
     "expr": "near_validator_active_total{job=\"$job\"}",
     "legendFormat": "Count"
    }
   ]
  },
  {
   "title": "Peers data received",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 7, "x": 1, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "rate(near_peer_data_received_bytes{job=\"$job\"}[1m])",
     "legendFormat": "Bytes"
    }
   ]
  },
  {
   "title": "Transaction per minute",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 8, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(near_transaction_processed_total{job=\"$job\"}[1m])",
     "legendFormat": "Count"
    }
   ]
  },
  {
   "title": "Burning",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 14, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(near_balance_burnt{job=\"$job\"}[1m]) * 0.000000000000000000000001",
     "legendFormat": "NEAR Tokens"
    }
   ]
  },
  {
   "title": "Disk Usage",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 1, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "1.0 - node_filesystem_free_bytes{fstype=~\"ext.\"} / node_filesystem_size_bytes{fstype=~\"ext.\"}",
     "legendFormat": "{{job}} - {{device}}"
    }
   ]
  },
  {
   "title": "CPU Load",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 7, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(irate(node_cpu_seconds_total{mode=\"user\"}[1m])) by (job) / count(node_cpu_seconds_total{mode=\"user\"}) by (job)",
     "legendFormat": "{{ job }}"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 7, "x": 13, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "(node_memory_MemTotal_bytes - node_memory_MemAvailable_bytes) / node_memory_MemTotal_bytes",
     "legendFormat": "{{ job }}"
    }
   ]
  }
 ]
}